# debug: true
spring.output.ansi.enabled: NEVER

# logging.config=file:./logback.xml
# logging.config=file:./log4j.xml

datasource.ladok2read.driver-class-name: com.mysql.jdbc.Driver
datasource.ladok2read.url: jdbc:mysql://CHANGEME:3306/uu?verifyServerCertificate=false&useSSL=true&requireSSL=true
datasource.ladok2read.username: CHANGEME
datasource.ladok2read.password: CHANGEME

datasource.sp.driver-class-name: com.ibm.db2.jcc.DB2Driver
datasource.sp.url: jdbc:db2://CHANGEME:PORT/DB:retrieveMessagesFromServerOnGetMessage=true;
datasource.sp.username: CHANGEME
datasource.sp.password: CHANGEME

datasource.esb.driver-class-name: org.hsqldb.jdbcDriver
datasource.esb.url: jdbc:hsqldb:file:target/hsqldb;sql.syntax_mys=true
datasource.esb.username: sa
datasource.esb.password: 

app.AcceptedEventService.updateAcceptedMembers.delay: 30000
